### PR TITLE
Improve storage

### PR DESCRIPTION
**Pull request by Arzumirzeb**
Here, I have implemented new methods get and count. Get method returns instance for given class name and id. Count method return number of instances for given class. If class is None, return number of all objects.

### CODE REVIEW

**Review by LGunay — APPROVED** [review]
These implementations are acceptable. Let's merge them.

**Comment by kazimovzaman2** [comment]
Cool

**Comment by Arzumirzeb** [comment]
> Cool

🐗

**Comment by isaquliyev** [comment]
> > Cool
> 
> 🐗

🍃🐗 Step into the enchanted woods, where the boar reigns supreme, its noble silhouette a testament to strength and resilience 🌟🌳

**Comment by Arzumirzeb** [comment]
> > > Cool
> > 
> > 
> > 🐗
> 
> 🍃🐗 Step into the enchanted woods, where the boar reigns supreme, its noble silhouette a testament to strength and resilience 🌟🌳

🙏🏻🐗

**Pull request merged**
